[2025-04-22T03:07:07.382-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T03:07:07.387-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:02:02.019155+00:00 [queued]>
[2025-04-22T03:07:07.389-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:02:02.019155+00:00 [queued]>
[2025-04-22T03:07:07.389-0400] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-22T03:07:07.398-0400] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_notebook> on 2025-04-22 07:02:02.019155+00:00
[2025-04-22T03:07:07.399-0400] {standard_task_runner.py:72} INFO - Started process 10963 to run task
[2025-04-22T03:07:07.401-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fashion_data_pipeline', 'execute_notebook', 'manual__2025-04-22T07:02:02.019155+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/FashionData_DAG.py', '--cfg-path', '/tmp/tmp1kipwtbl']
[2025-04-22T03:07:07.402-0400] {standard_task_runner.py:105} INFO - Job 25: Subtask execute_notebook
[2025-04-22T03:07:07.429-0400] {task_command.py:467} INFO - Running <TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:02:02.019155+00:00 [running]> on host BOOK-KTS1KMKSNJ.
[2025-04-22T03:07:07.463-0400] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fashion_data_pipeline' AIRFLOW_CTX_TASK_ID='execute_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T07:02:02.019155+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T07:02:02.019155+00:00'
[2025-04-22T03:07:07.464-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T03:07:07.464-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T03:07:07.464-0400] {logging_mixin.py:190} INFO - Current task name:execute_notebook state:running start_date:2025-04-22 07:07:07.387206+00:00
[2025-04-22T03:07:07.464-0400] {logging_mixin.py:190} INFO - Dag name:fashion_data_pipeline and current dag run status:running
[2025-04-22T03:07:07.465-0400] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T03:07:07.468-0400] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 31, in execute_notebook
    raise AirflowException("AIRFLOW_HOME environment variable is not set.")
airflow.exceptions.AirflowException: AIRFLOW_HOME environment variable is not set.
[2025-04-22T03:07:07.471-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-22T03:07:07.472-0400] {logging_mixin.py:190} INFO - Task start:2025-04-22 07:07:07.387206+00:00 end:2025-04-22 07:07:07.471564+00:00 duration:0.084358
[2025-04-22T03:07:07.472-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): execute_notebook> dag:<DAG: fashion_data_pipeline> dagrun:<DagRun fashion_data_pipeline @ 2025-04-22 07:02:02.019155+00:00: manual__2025-04-22T07:02:02.019155+00:00, state:running, queued_at: 2025-04-22 07:02:02.027071+00:00. externally triggered: True>
[2025-04-22T03:07:07.472-0400] {logging_mixin.py:190} INFO - Failure caused by AIRFLOW_HOME environment variable is not set.
[2025-04-22T03:07:07.472-0400] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=fashion_data_pipeline, task_id=execute_notebook, run_id=manual__2025-04-22T07:02:02.019155+00:00, execution_date=20250422T070202, start_date=20250422T070707, end_date=20250422T070707
[2025-04-22T03:07:07.487-0400] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T03:07:07.487-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task execute_notebook (AIRFLOW_HOME environment variable is not set.; 10963)
Traceback (most recent call last):
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 31, in execute_notebook
    raise AirflowException("AIRFLOW_HOME environment variable is not set.")
airflow.exceptions.AirflowException: AIRFLOW_HOME environment variable is not set.
[2025-04-22T03:07:07.494-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T03:07:07.502-0400] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T03:07:07.503-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
