[2025-04-22T03:26:24.099-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T03:26:24.104-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:26:20.903332+00:00 [queued]>
[2025-04-22T03:26:24.107-0400] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:26:20.903332+00:00 [queued]>
[2025-04-22T03:26:24.108-0400] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-22T03:26:24.120-0400] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_notebook> on 2025-04-22 07:26:20.903332+00:00
[2025-04-22T03:26:24.123-0400] {standard_task_runner.py:72} INFO - Started process 12904 to run task
[2025-04-22T03:26:24.125-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fashion_data_pipeline', 'execute_notebook', 'manual__2025-04-22T07:26:20.903332+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/FashionData_DAG.py', '--cfg-path', '/tmp/tmpxtkjhyzj']
[2025-04-22T03:26:24.126-0400] {standard_task_runner.py:105} INFO - Job 38: Subtask execute_notebook
[2025-04-22T03:26:24.153-0400] {task_command.py:467} INFO - Running <TaskInstance: fashion_data_pipeline.execute_notebook manual__2025-04-22T07:26:20.903332+00:00 [running]> on host BOOK-KTS1KMKSNJ.
[2025-04-22T03:26:24.186-0400] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fashion_data_pipeline' AIRFLOW_CTX_TASK_ID='execute_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T07:26:20.903332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T07:26:20.903332+00:00'
[2025-04-22T03:26:24.187-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T03:26:24.187-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T03:26:24.187-0400] {logging_mixin.py:190} INFO - Current task name:execute_notebook state:running start_date:2025-04-22 07:26:24.104312+00:00
[2025-04-22T03:26:24.187-0400] {logging_mixin.py:190} INFO - Dag name:fashion_data_pipeline and current dag run status:running
[2025-04-22T03:26:24.187-0400] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T03:26:24.188-0400] {FashionData_DAG.py:58} INFO - Executing notebook: /home/megin_mathew/airflow/notebooks/Fashion_Data_Pipeline.ipynb
[2025-04-22T03:26:24.188-0400] {FashionData_DAG.py:59} INFO - Output will be saved to: /home/megin_mathew/airflow/notebook_outputs/Fashion_Data_Pipeline-output-2025-04-22.ipynb
[2025-04-22T03:26:24.188-0400] {FashionData_DAG.py:60} INFO - Parameters passed to notebook: {'execution_date': '2025-04-22T07:26:20.903332+00:00', 'dag_run_id': 'manual__2025-04-22T07:26:20.903332+00:00', 'ds': '2025-04-22', 'ds_nodash': '20250422'}
[2025-04-22T03:26:24.188-0400] {execute.py:83} INFO - Input Notebook:  /home/megin_mathew/airflow/notebooks/Fashion_Data_Pipeline.ipynb
[2025-04-22T03:26:24.188-0400] {execute.py:84} INFO - Output Notebook: /home/megin_mathew/airflow/notebook_outputs/Fashion_Data_Pipeline-output-2025-04-22.ipynb
[2025-04-22T03:26:25.343-0400] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2025-04-22T03:26:25.343-0400] {engines.py:223} INFO - Executing Cell 1---------------------------------------
[2025-04-22T03:26:25.352-0400] {engines.py:261} INFO - Ending Cell 1------------------------------------------
[2025-04-22T03:26:25.354-0400] {engines.py:223} INFO - Executing Cell 2---------------------------------------
[2025-04-22T03:26:25.361-0400] {engines.py:261} INFO - Ending Cell 2------------------------------------------
[2025-04-22T03:26:25.362-0400] {engines.py:223} INFO - Executing Cell 3---------------------------------------
[2025-04-22T03:26:25.832-0400] {clientwrap.py:91} INFO - Requirement already satisfied: kagglehub in ./airflow_venv/lib/python3.12/site-packages (0.3.11)
Requirement already satisfied: pandas in ./airflow_venv/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: psycopg2-binary in ./airflow_venv/lib/python3.12/site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in ./airflow_venv/lib/python3.12/site-packages (1.4.54)
Requirement already satisfied: packaging in ./airflow_venv/lib/python3.12/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in ./airflow_venv/lib/python3.12/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in ./airflow_venv/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in ./airflow_venv/lib/python3.12/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: numpy>=1.26.0 in ./airflow_venv/lib/python3.12/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./airflow_venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./airflow_venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./airflow_venv/lib/python3.12/site-packages (from pandas) (2025.2)

[2025-04-22T03:26:25.883-0400] {clientwrap.py:91} INFO - Requirement already satisfied: greenlet!=0.4.17 in ./airflow_venv/lib/python3.12/site-packages (from sqlalchemy) (3.2.0)
Requirement already satisfied: six>=1.5 in ./airflow_venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in ./airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./airflow_venv/lib/python3.12/site-packages (from requests->kagglehub) (2025.1.31)

[2025-04-22T03:26:26.272-0400] {engines.py:261} INFO - Ending Cell 3------------------------------------------
[2025-04-22T03:26:26.274-0400] {engines.py:223} INFO - Executing Cell 4---------------------------------------
[2025-04-22T03:26:26.352-0400] {clientwrap.py:91} INFO - ['KaggleDatasetAdapter', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'auth', 'cache', 'clients', 'colab_cache_resolver', 'competition', 'competition_download', 'config', 'dataset_download', 'dataset_load', 'dataset_upload', 'datasets', 'datasets_enums', 'datasets_helpers', 'env', 'exceptions', 'gcs_upload', 'get_package_asset_path', 'handle', 'http_resolver', 'integrity', 'kaggle_cache_resolver', 'kagglehub', 'load_dataset', 'logger', 'login', 'model_download', 'model_upload', 'models', 'models_helpers', 'notebook_output_download', 'notebooks', 'package_import', 'packages', 'registry', 'resolver', 'signing', 'tracker', 'utility_script_install', 'utility_scripts', 'whoami']

[2025-04-22T03:26:26.352-0400] {clientwrap.py:98} WARNING - /home/megin_mathew/airflow_venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[2025-04-22T03:26:26.354-0400] {engines.py:261} INFO - Ending Cell 4------------------------------------------
[2025-04-22T03:26:26.356-0400] {engines.py:223} INFO - Executing Cell 5---------------------------------------
[2025-04-22T03:26:26.824-0400] {clientwrap.py:91} INFO - Requirement already satisfied: kaggle in ./airflow_venv/lib/python3.12/site-packages (1.7.4.2)
Requirement already satisfied: bleach in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (79.0.0)
Requirement already satisfied: six>=1.10 in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in ./airflow_venv/lib/python3.12/site-packages (from kaggle) (0.5.1)

[2025-04-22T03:26:27.181-0400] {clientwrap.py:91} INFO - Note: you may need to restart the kernel to use updated packages.

[2025-04-22T03:26:27.183-0400] {engines.py:261} INFO - Ending Cell 5------------------------------------------
[2025-04-22T03:26:27.185-0400] {engines.py:223} INFO - Executing Cell 6---------------------------------------
[2025-04-22T03:26:27.271-0400] {clientwrap.py:91} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/megin_mathew/.config/kaggle/kaggle.json'
Kaggle module is successfully installed!

[2025-04-22T03:26:27.272-0400] {engines.py:261} INFO - Ending Cell 6------------------------------------------
[2025-04-22T03:26:27.275-0400] {engines.py:223} INFO - Executing Cell 7---------------------------------------
[2025-04-22T03:26:27.281-0400] {clientwrap.py:91} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/megin_mathew/.config/kaggle/kaggle.json'
Kaggle API authentication successful!

[2025-04-22T03:26:27.283-0400] {engines.py:261} INFO - Ending Cell 7------------------------------------------
[2025-04-22T03:26:27.285-0400] {engines.py:223} INFO - Executing Cell 8---------------------------------------
[2025-04-22T03:27:26.235-0400] {clientwrap.py:91} INFO - Downloaded: transactions.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:30.259-0400] {clientwrap.py:98} WARNING - /home/megin_mathew/airflow_venv/lib/python3.12/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

[2025-04-22T03:27:34.359-0400] {clientwrap.py:91} INFO - Downloaded: customers.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:34.764-0400] {clientwrap.py:91} INFO - Downloaded: discounts.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:35.035-0400] {clientwrap.py:91} INFO - Downloaded: employees.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:35.607-0400] {clientwrap.py:91} INFO - Downloaded: products.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:35.701-0400] {clientwrap.py:91} INFO - Downloaded: stores.csv → Stored in: C:/Users/megin/fashion_dataset

[2025-04-22T03:27:35.705-0400] {engines.py:261} INFO - Ending Cell 8------------------------------------------
[2025-04-22T03:27:35.709-0400] {engines.py:223} INFO - Executing Cell 9---------------------------------------
[2025-04-22T03:27:35.723-0400] {engines.py:261} INFO - Ending Cell 9------------------------------------------
[2025-04-22T03:27:35.725-0400] {engines.py:223} INFO - Executing Cell 10--------------------------------------
[2025-04-22T03:27:35.728-0400] {engines.py:261} INFO - Ending Cell 10-----------------------------------------
[2025-04-22T03:27:35.730-0400] {engines.py:223} INFO - Executing Cell 11--------------------------------------
[2025-04-22T03:27:36.676-0400] {clientwrap.py:98} WARNING - JAVA_HOME is not set
2025-04-22 03:27:36,660 - ERROR - Failed to create Spark session: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

[2025-04-22T03:27:37.000-0400] {engines.py:261} INFO - Ending Cell 11-----------------------------------------
[2025-04-22T03:27:37.643-0400] {FashionData_DAG.py:89} ERROR - Failed to execute notebook: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

[2025-04-22T03:27:37.684-0400] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 68, in execute_notebook
    pm.execute_notebook(
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 91, in execute_notebook
    raise AirflowException(f"Notebook execution failed: {str(e)}")
airflow.exceptions.AirflowException: Notebook execution failed: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

[2025-04-22T03:27:37.706-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-22T03:27:37.706-0400] {logging_mixin.py:190} INFO - Task start:2025-04-22 07:26:24.104312+00:00 end:2025-04-22 07:27:37.704308+00:00 duration:73.599996
[2025-04-22T03:27:37.707-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): execute_notebook> dag:<DAG: fashion_data_pipeline> dagrun:<DagRun fashion_data_pipeline @ 2025-04-22 07:26:20.903332+00:00: manual__2025-04-22T07:26:20.903332+00:00, state:running, queued_at: 2025-04-22 07:26:20.930194+00:00. externally triggered: True>
[2025-04-22T03:27:37.707-0400] {logging_mixin.py:190} INFO - Failure caused by Notebook execution failed: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-04-22T03:27:37.708-0400] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=fashion_data_pipeline, task_id=execute_notebook, run_id=manual__2025-04-22T07:26:20.903332+00:00, execution_date=20250422T072620, start_date=20250422T072624, end_date=20250422T072737
[2025-04-22T03:27:37.750-0400] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T03:27:37.751-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task execute_notebook (Notebook execution failed: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
; 12904)
Traceback (most recent call last):
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 68, in execute_notebook
    pm.execute_notebook(
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/megin_mathew/airflow/dags/FashionData_DAG.py", line 91, in execute_notebook
    raise AirflowException(f"Notebook execution failed: {str(e)}")
airflow.exceptions.AirflowException: Notebook execution failed: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
PySparkRuntimeError                       Traceback (most recent call last)
Cell In[10], line 56
     53         raise
     55 # Initialize Spark
---> 56 spark = create_spark_session()
     58 # Load environment variables
     59 load_dotenv()

Cell In[10], line 50, in create_spark_session()
     35     if not os.path.exists(temp_dir):
     36         os.makedirs(temp_dir)
     38     return SparkSession.builder \
     39         .appName("GlobalFashionRetailDataLoader") \
     40         .config("spark.local.dir", temp_dir) \
     41         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
     42         .config("spark.executor.memory", "8g") \
     43         .config("spark.driver.memory", "8g") \
     44         .config("spark.memory.offHeap.enabled", "false") \
     45         .config("spark.sql.shuffle.partitions", "200") \
     46         .config("spark.default.parallelism", "200") \
     47         .config("spark.sql.adaptive.enabled", "true") \
     48         .config("spark.network.timeout", "600s") \
     49         .config("spark.executor.heartbeatInterval", "60s") \
---> 50         .getOrCreate()
     51 except Exception as e:
     52     logger.error(f"Failed to create Spark session: {str(e)}")

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
    495     sparkConf.set(key, value)
    496 # This SparkContext may be an existing one.
--> 497 sc = SparkContext.getOrCreate(sparkConf)
    498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
    499 # by all sessions.
    500 session = SparkSession(sc, options=self._options)

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
    513 with SparkContext._lock:
    514     if SparkContext._active_spark_context is None:
--> 515         SparkContext(conf=conf or SparkConf())
    516     assert SparkContext._active_spark_context is not None
    517     return SparkContext._active_spark_context

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
    195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
    196     raise ValueError(
    197         "You are trying to pass an insecure Py4j gateway to Spark. This"
    198         " is not allowed as it is a security risk."
    199     )
--> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    202 try:
    203     self._do_init(
    204         master,
    205         appName,
   (...)    215         memory_profiler_cls,
    216     )

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
    434 with SparkContext._lock:
    435     if not SparkContext._gateway:
--> 436         SparkContext._gateway = gateway or launch_gateway(conf)
    437         SparkContext._jvm = SparkContext._gateway.jvm
    439     if instance:

File ~/airflow_venv/lib/python3.12/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
    104     time.sleep(0.1)
    106 if not os.path.isfile(conn_info_file):
--> 107     raise PySparkRuntimeError(
    108         error_class="JAVA_GATEWAY_EXITED",
    109         message_parameters={},
    110     )
    112 with open(conn_info_file, "rb") as info:
    113     gateway_port = read_int(info)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

[2025-04-22T03:27:37.801-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T03:27:37.838-0400] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T03:27:37.838-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
